FROM node:22-slim

WORKDIR /app

COPY /out/apps/client .

RUN npm install

RUN npm run build

# Copy public + static into standalone
RUN cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/

EXPOSE 3002

ENV PORT=3002

CMD ["node", ".next/standalone/server.js"]