name: CI/CD for TurboRepo with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies for production using npm
        if: github.ref == 'refs/heads/main'
        run: npm install

      - name: Install TurboRepo
        run: npm install --global turbo

      - name: Build Docker image for Next.js (client)
        run: |
          docker build -f Dockerfile.cicd-client -t anhntserver/my-app-client:latest .

      - name: Build Docker image for Nest.js (server)
        run: |
          docker build -f Dockerfile.cicd-server -t anhntserver/my-app-server:latest .
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push anhntserver/my-app-client:latest
          docker push anhntserver/my-app-server:latest
  deploy:
    needs: push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "Deploy step"
      - name: SSH to deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 171.248.147.82
          username: master
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat <<EOF > my-app-client-deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: my-app-client
              labels:
                app: my-app-client
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: my-app-client
              template:
                metadata:
                  labels:
                    app: my-app-client
                spec:
                  containers:
                    - name: my-app-client
                      image: anhntserver/my-app-client:latest
                      ports:
                      - containerPort: 3002
            EOF

            cat <<EOF > my-app-client-service.yaml
            apiVersion: v1
            kind: Service
            metadata:
              name: my-app-client-service
            spec:
              selector:
                app: my-app-client
              ports:
                - port: 11001
                  targetPort: 3002
              type: LoadBalancer
            EOF

            cat <<EOF > my-app-client-ingress-service.yaml
            apiVersion: v1
            kind: Service
            metadata:
              name: my-app-client-ingress-service
            spec:
              type: ClusterIP
              ports:
                  - port: 9001
                    targetPort: 3002
                    protocol: TCP
              selector:
                  app: my-app-client
            EOF

            cat <<EOF > my-app-client-ingress.yaml
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: my-app-client-ingress
              annotations:
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            spec:
              ingressClassName: nginx
              tls:
              - hosts: 
                - my-app.freedomwalking.net
                secretName: dummy-tls-secret-01
              rules:
              - host: my-app.freedomwalking.net
                http:
                  paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: my-app-client-ingress-service
                        port:
                          number: 9001
            EOF

            kubectl apply -f my-app-client-deployment.yaml
            kubectl apply -f my-app-client-service.yaml
            kubectl apply -f my-app-client-ingress.yaml
            kubectl apply -f my-app-client-ingress-service.yaml

            cat <<EOF > my-app-server-deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: my-app-server
              labels:
                app: my-app-server
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: my-app-server
              template:
                metadata:
                  labels:
                    app: my-app-server
                spec:
                  containers:
                  - name: my-app-server
                    image: anhntserver/my-app-server:latest
                    ports:
                    - containerPort: 3001
            EOF

            cat <<EOF > my-app-server-service.yaml
            apiVersion: v1
            kind: Service
            metadata:
              name: my-app-server-service
            spec:
              selector:
                app: my-app-server
              ports:
                - port: 11002
                  targetPort: 3001
              type: LoadBalancer
            EOF

            cat <<EOF > my-app-server-ingress-service.yaml
            apiVersion: v1
            kind: Service
            metadata:
              name: my-app-server-ingress-service
            spec:
              type: ClusterIP
              ports:
                  - port: 9002
                    targetPort: 3001
                    protocol: TCP
              selector:
                  app: my-app-server
            EOF

            cat <<EOF > my-app-server-ingress.yaml
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: my-app-server-ingress
              annotations:
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            spec:
              ingressClassName: nginx
              tls:
              - hosts: 
                - my-app-server.freedomwalking.net
                secretName: dummy-tls-secret-02
              rules:
              - host: my-app-server.freedomwalking.net
                http:
                  paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: my-app-server-ingress-service
                        port:
                          number: 9002
            EOF

            kubectl apply -f my-app-server-deployment.yaml
            kubectl apply -f my-app-server-service.yaml
            kubectl apply -f my-app-server-ingress.yaml
            kubectl apply -f my-app-server-ingress-service.yaml
