name: CI/CD for TurboRepo with Docker

on:
  push:
    branches:
      - main # Hoặc branch bạn muốn theo dõi
  pull_request:
    branches:
      - main # Hoặc branch bạn muốn theo dõi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Nếu môi trường là production, chạy npm install thay vì pnpm
      - name: Install dependencies for production using npm
        if: github.ref == 'refs/heads/main'
        run: npm install

      - name: Install TurboRepo
        run: npm install --global turbo

      - name: Build Docker image for Next.js (client)
        run: |
          docker build -f DockerfileCI.client -t anhntserver/my-app-client:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push anhntserver/my-app-client:latest

      - name: SSH to deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 192.168.1.151
          username: master
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull anhntserver/my-app-client:latest
